// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4eiJJsoTVDclEE2vhct9riN_gy3a1Bk',
    appId: '1:526376898313:web:09464b78dae35ee8e5cdd8',
    messagingSenderId: '526376898313',
    projectId: 'isiapp-fb5f4',
    authDomain: 'isiapp-fb5f4.firebaseapp.com',
    storageBucket: 'isiapp-fb5f4.appspot.com',
    measurementId: 'G-TENJFE1B3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiaBnpqa_gDvV1GfBw3M02-RNyPfDDm20',
    appId: '1:526376898313:android:0e8bbfb229054a06e5cdd8',
    messagingSenderId: '526376898313',
    projectId: 'isiapp-fb5f4',
    storageBucket: 'isiapp-fb5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrqOy9i1mW1-_wt6EjtA7dIqC5AeKN1iY',
    appId: '1:526376898313:ios:22cbc93df9b82d06e5cdd8',
    messagingSenderId: '526376898313',
    projectId: 'isiapp-fb5f4',
    storageBucket: 'isiapp-fb5f4.appspot.com',
    iosBundleId: 'com.example.isiStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrqOy9i1mW1-_wt6EjtA7dIqC5AeKN1iY',
    appId: '1:526376898313:ios:22cbc93df9b82d06e5cdd8',
    messagingSenderId: '526376898313',
    projectId: 'isiapp-fb5f4',
    storageBucket: 'isiapp-fb5f4.appspot.com',
    iosBundleId: 'com.example.isiStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4eiJJsoTVDclEE2vhct9riN_gy3a1Bk',
    appId: '1:526376898313:web:c90bb17e3c99865de5cdd8',
    messagingSenderId: '526376898313',
    projectId: 'isiapp-fb5f4',
    authDomain: 'isiapp-fb5f4.firebaseapp.com',
    storageBucket: 'isiapp-fb5f4.appspot.com',
    measurementId: 'G-QP2FBEL191',
  );
}
