name: isi_student
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  fluttertoast: ^8.2.4
  image_picker: ^0.8.4+4
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  provider: ^6.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.12
  firebase_messaging: ^14.8.1
  firebase_analytics: ^10.10.1
  flutter_local_notifications: ^17.0.1
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg.png
    