name: isi_admin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.2.4
  image_picker: ^0.8.4+4
  firebase_storage: ^11.7.1
  animated_splash_screen: ^1.3.0
  file_picker: ^8.0.0+1
  image_cropper: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  